---
  root: ./

  run_name: regressor #update for specific run name
  path_out:  ModelOutput/ #root + folder
  path_in:  predictions/ens/ #root + folder

  prediction:  data/prediction.csv #root + folder
  targets:  data/targets.csv #root + folder
  training:  data/training.csv

  predictors: ["feature_1", "feature_2", "feature_3"]

  verbose: 1 # scikit-learn warning verbosity
  seed : 1 # random seed
  n_threads : 1 # how many cpu threads to use
  cv : 5 # number of cross folds

  ensemble_config: 
    classifier: False
    regressor: True
    m1: "rf"
    m2: "xgb"
    m3: "knn"

  upsample: False
  stratify: False

  reg_scoring:
   R2: r2
   MAE: neg_mean_absolute_error
   RMSE: neg_root_mean_squared_error

  param_grid:
    rf_param_grid:
      reg_param_grid:
        n_estimators: [100]
        max_features: [0.2, 0.4, 0.8]
        max_depth: [50]
        min_samples_leaf: [0.5]
        max_samples: [0.5]     

    xgb_param_grid:
      reg_param_grid:  
        learning_rate: [0.05]
        n_estimators: [100]
        max_depth: [7]
        subsample: [0.8]  
        colsample_bytree: [0.5]
        gamma: [1] 
        reg_alpha: [0.1]   

    knn_param_grid:
      reg_param_grid:  
        max_samples: [0.85]
        max_features: [0.85]
        estimator__leaf_size: [5]
        estimator__n_neighbors: [5]
        estimator__p:  [1]        
        estimator__weights: ["uniform"]

  knn_bagging_estimators: 30

